### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by purvasharmadev**
# Changes I did:

- Added Routes
> To Check : routes.js

- Added a custom hook to get products
> To Check: useGetProducts.js

-  Abstracted the repeating code i.e created Components like 
>ignore:  Banner.jsx , Footer.jsx

- Renamed files for better understanding
> Ignore: 'LandingPage' to 'Home-Page' , 'Card' to 'ProductCard'

### CODE REVIEW

**Review by itsmebipul00 — APPROVED** [review]
Nice Work, Clean Code, Nice thing done with URL Routes
Small Suggestion: You could create a separate Loader, Error Components

**Review by archit7448 — APPROVED** [review]
Good work! looks good to merge

**Comment by purvasharmadev** [comment]
> Nice Work, Clean Code, Nice thing done with URL Routes Small Suggestion: You could create a separate Loader, Error Components

Thank you for the suggestion, will try that!

**Comment by purvasharmadev** [comment]
> Good work! looks good to merge

Thank you for approving.

**Pull request merged**
